### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by michal-bootcamp** [lucluba/Ex8.6#1]
Troche nie wiadomo, co tu sie wlasciwie dzieje. Rozumiem, ze sa rozne metody, ale zgodnie z zadaniem oczekiwalbym, ze wpisze dwie liczby i dostane wynik dzialania oraz informacje, czy wynik jest dodatni/ujemny/zero. Tylko tyle, bez komplikacji. Najlepiej jak wyniki beda sie pojawiac w konsoli, a nie w alercie.

**Comment by lucluba** [comment]
Ogólnie wiem dlaczego zmieniłem to na parzyste i nieparzyste i testowałem sobie wszystkie te możliwości z modułu 8.6.

**Comment by michal-bootcamp** [comment]
ok, pare uwag:
1. `console.log(value = (a * a) + (2 * a * b) - (b * b));` tutaj rozumiem Twoj skrot, ze od razu przypisujesz dzialanie do `value`, ale lepiej byloby przypisac to wczesniej i wyswietlic `value` w console.logu. Taki skrot bylby dobry gdybys nie potrzebowal dalej value i mogl wyswietlic sam wynik dzialania bez niepotrzebnego tworzenia zmiennej, czyli `console.log((a * a) + (2 * a * b) - (b * b));`, ale jesli uzywasz value to i tak musisz to przypisac wiec czytelniej bedzie to zrobic poza console.logiem
2. zamien dwa `if...else` na jeden `if` z dwoma else, zeby pojawial sie tylko jeden komunikat w konsoli (wynik wiekszy od 0 /  rowny 0 / mniejszy od 0). Teraz jak wpisze 0, to dostaje dwa komunikaty:
`Result of your function is positive`
`Result of your function is zero`
co nie jest prawidlowe :)
